// Generated by Wrangler on Tue Aug 13 2024 15:12:45 GMT+0200 (Central European Summer Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	KV: KVNamespace;
	OPENWEATHER_API_KEY: "56c81a15d3b9f861afb6d9c97ba6f1e5";
	BUCKET: R2Bucket;
	DB: D1Database;
	AI: Ai;
}
