#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-poem"
main = "src/index.ts"
compatibility_date = "2024-08-06"

[[d1_databases]]
binding = "DB"
database_name = "cloudflare-poem-db"
database_id = "ebf949ce-56e8-4d98-ad63-a7ba7aa8df64"
migrations_dir = "drizzle/migrations"

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'cloudflare-poem-bucket'

[triggers]
crons = [ "* * * * *" ]

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "KV"
id = "f1c144608d9c4a1991c98a966e800934"

[vars]
OPENWEATHER_API_KEY = "56c81a15d3b9f861afb6d9c97ba6f1e5"
